make addrev exit with 1 in case of failure
improve hint on using --prnum=... in review-tools/addrev

Various tweaks to make ghmerge more usable

- make gcc (rather than clang-3.6) the default for rebuilding
- take the (SSH version of the) repo URL from the database
- add 'git pull' to get the latest state of the master
- add '-i --autosquash' to 'git rebase' and move it before addrev
- make '--nomerge' (which means interactive rebase) the default
- show the log of the commits be pushed (after addrev is called)
- print some more (and slightly improved) info what is going on
- tweak the safety questions being asked

extend and update documentation of addrev etc. in review-tools/README

add info on HTTPS transfer done by (git)addrev and ghmerge
also on use of 'https_proxy' and 'no_proxy' env variables

* extend general description
* make clear that ghmerge calls addrev
* add description of the ghmerge options

Reviewed-by: Tomas Mraz <tmraz@fedoraproject.org>
Reviewed-by: Paul Dale <paul.dale@oracle.com>
(Merged from https://github.com/openssl/openssl/pull/59)

diff --git a/review-tools/ghmerge b/review-tools/ghmerge
--- a/review-tools/ghmerge
+++ b/review-tools/ghmerge
@@ -5,7 +5,10 @@ set -o errexit
 WHAT=openssl
 BUILD=yes
 TRIVIAL=""
-MERGE="yes"
+INTERACTIVE=yes
+AUTOSQUASH="--autosquash"
+[ -z ${CC+x} ] && CC="ccache gcc" # the default otherwise is "ccache clang-3.6"
+REMOTE=`git remote -v | awk '/git.openssl.org.*(push)/{ print $1; }' | head -n 1`
 
 if [ ! -d .git ] ; then
     echo Not at top-level
@@ -16,22 +19,29 @@ fi
 while true ; do
     case "$1" in
     --tools)
-        WHAT=tools ; MERGE=yes ; BUILD=no ; shift
+        WHAT=tools ; BUILD=no ; shift
         ;;
     --web)
-        WHAT=web ; MERGE=yes ; BUILD=no ; shift
+        WHAT=web ; BUILD=no ; shift
         ;;
     --trivial)
         TRIVIAL="--trivial" ; shift
         ;;
-    --merge | --squash)
-        MERGE=yes ; shift
+    --noautosquash)
+        AUTOSQUASH="" ; shift
         ;;
-    --nomerge | --nosquash)
-        MERGE=no ; shift
+    --squash)
+        INTERACTIVE=no ; shift
         ;;
     --nobuild)
         BUILD=no ; shift
+        ;;
+    --remote)
+        if [ $# -lt 2 ] ; then
+            echo "Missing argument of '$1'"
+            exit 1
+        fi
+        shift; REMOTE=$1; shift
         ;;
     --)
         shift
@@ -54,14 +64,21 @@ fi
 PRNUM=$1 ; shift
 TEAM=$*
 
-curl -s https://api.github.com/repos/openssl/$WHAT/pulls/$PRNUM >/tmp/gh$$
+PR_URL=https://api.github.com/repos/openssl/$WHAT/pulls/$PRNUM
+if ! wget --quiet $PR_URL -O /tmp/gh$$; then
+    echo "Error getting $PR_URL"
+    exit 1
+fi
 set -- `python -c '
 from __future__ import print_function
 import json, sys;
-print(str(json.load(sys.stdin)["head"]["label"]).replace(":", " "))' </tmp/gh$$`
-rm /tmp/gh$$
+input = json.load(sys.stdin)
+print(str(input["head"]["label"]).replace(":", " "),
+      str(input["head"]["repo"]["ssh_url"]))'        </tmp/gh$$`
 WHO=$1
 BRANCH=$2
+REPO=$3
+rm /tmp/gh$$
 
 if [ -z "$WHO" -o -z "$BRANCH" ]; then
     echo "Don't know from which branch to fetch"
@@ -72,40 +89,59 @@ REL=`git rev-parse --abbrev-ref HEAD`
 WORK="${WHO}-${BRANCH}"
 PREV=
 
-git checkout -b $WORK $REL
+echo -n "Press Enter to pull the latest $REL from $REMOTE: "; read foo
+git pull $REMOTE $REL
 
 function cleanup {
     if [ "$WORK" != "$REL" ]; then
         git checkout -q $REL
         git branch -D $WORK
+        git reset --hard $REMOTE/$REL
     fi
 }
 trap 'cleanup' EXIT
 
-git pull --rebase https://github.com/$WHO/$WHAT.git $BRANCH
-git rebase $REL
+git checkout -b $WORK $REL
+
+# append new commits from $REPO/$BRANCH
+git pull --rebase $REPO $BRANCH
+echo rebasing on $REL
+git rebase $REL || (git rebase --abort; exit 1)
 
 echo Diff against $REL
 git diff $REL
 
-echo -n Press return to merge to $REL: ; read foo
-addrev $TRIVIAL --prnum=$PRNUM $TEAM ${REL}..
-git checkout $REL
-if [ "$MERGE" == "yes" ] ; then
-    git merge --no-commit --squash $WORK
-    AUTHOR=`git show --no-patch --pretty="format:%an <%ae>" $WORK`
-    git commit --author="$AUTHOR"
-else
-    git rebase $WORK
+if [ "$INTERACTIVE" == "yes" ] ; then
+    # echo -n "Press Enter to interactively rebase $AUTOSQUASH on $REL: "; read foo
+    git rebase -i $AUTOSQUASH $REL || (git rebase --abort; exit 1)
+    addrev $TRIVIAL --prnum=$PRNUM $TEAM ${REL}..
 fi
 
+echo Log since $REL
+git log $REL..
+
+git checkout $REL
+if [ "$INTERACTIVE" != "yes" ] ; then
+    echo -n "Press Enter to non-interactively merge --squash to $REL: "; read foo
+    git merge --ff-only --no-commit --squash $WORK
+    AUTHOR=`git show --no-patch --pretty="format:%an <%ae>" $WORK`
+    git commit --author="$AUTHOR"
+    addrev $TRIVIAL --prnum=$PRNUM $TEAM $REMOTE/${REL}..
+else
+    # echo -n "Press Enter to merge to $REL: "; read foo
+    git merge --ff-only $WORK
+fi
+
+echo New log since $REMOTE/$REL
+git log $REMOTE/$REL..
+
 if [ "$BUILD" == "yes" ] ; then
-    echo Rebuilding
-    ( opensslbuild 2>&1 ) | tail -3
+    echo Rebuilding...
+    ( CC="$CC" opensslbuild 2>&1 ) | tail -3
 fi
 
 while true ; do
-    echo -n "Enter YES to push or NO to abort: "
+    echo -n "Enter 'yes' to push to $REMOTE/$REL or 'no' to abort: "
     read x
     x="`echo $x | tr A-Z a-z`"
     if [ "$x" = "y" -o "$x" = "yes" -o "$x" = "n" -o "$x" = "no" ] ; then
@@ -114,5 +150,5 @@ while true ; do
 done
 
 if [ "$x" = "y" -o "$x" = "yes" ] ; then
-    git push origin $REL
+    git push -v $REMOTE $REL
 fi
