ghmerge: Rename variable 'REL' to more telling 'REF'
Reviewed-by: Tomas Mraz <tmraz@fedoraproject.org>
Reviewed-by: Paul Dale <paul.dale@oracle.com>
(Merged from https://github.com/openssl/openssl/pull/72)

diff --git a/review-tools/ghmerge b/review-tools/ghmerge
--- a/review-tools/ghmerge
+++ b/review-tools/ghmerge
@@ -14,7 +14,7 @@ PICK=no
 INTERACTIVE=yes
 AUTOSQUASH="--autosquash"
 REMOTE=""
-REL=""
+REF=""
 BUILD=yes
 [ -z ${CC+x} ] && CC="ccache gcc" # opensslbuild will otherwise use "ccache clang-3.6"
 
@@ -60,7 +60,7 @@ while [ $# -ne 0 ]; do
             echo "Missing argument of '$1'"
             usage_exit
         fi
-        shift; REL=$1; shift
+        shift; REF=$1; shift
         ;;
     --)
         if [ $# -lt 3 ] ; then
@@ -127,14 +127,14 @@ if [ -z "$WHO" -o -z "$BRANCH" -o -z "$REPO" ]; then
     exit 1
 fi
 
-if [ "$REL" = "" ]; then
-    REL=`git rev-parse --abbrev-ref HEAD` # usually will be 'HEAD' or e.g., OpenSSL_1_1_1-stable
+if [ "$REF" = "" ]; then
+    REF=`git rev-parse --abbrev-ref HEAD` # usually will be 'HEAD' or e.g., OpenSSL_1_1_1-stable
 else
-    echo -n "Press Enter to checkout $REL: "; read foo
-    git checkout $REL
+    echo -n "Press Enter to checkout $REF: "; read foo
+    git checkout $REF
 fi
 
-echo -n "Press Enter to pull the latest $REMOTE/$REL: "; read foo
+echo -n "Press Enter to pull the latest $REMOTE/$REF: "; read foo
 git pull $REMOTE || (git rebase --abort; exit 1)
 
 WORK="copy-of-${WHO}-${BRANCH}"
@@ -143,53 +143,53 @@ function cleanup {
     rv=$?
     echo # new line
     [ $rv -ne 0 ] && echo -e "\nghmerge failed"
-    if [ "$WORK" != "$REL" ]; then
-        echo Restoring local $REL
-        git checkout -q $REL
+    if [ "$WORK" != "$REF" ]; then
+        echo Restoring local $REF
+        git checkout -q $REF
         git branch -qD $WORK 2>/dev/null
     fi
-    git reset --hard $REMOTE/$REL # prune any leftover commits added locally
+    git reset --hard $REMOTE/$REF # prune any leftover commits added locally
 }
 trap 'cleanup' EXIT
 
-git checkout -b $WORK $REL
+git checkout -b $WORK $REF
 
 # append new commits from $REPO/$BRANCH
 if [ "$PICK" != "yes" ]; then
-    echo Rebasing $REPO/$BRANCH on $REL...
+    echo Rebasing $REPO/$BRANCH on $REF...
     git pull --rebase $REPO $BRANCH || (git rebase --abort; exit 1)
 else
-    echo Cherry-picking $REPO/$BRANCH to $REL...
+    echo Cherry-picking $REPO/$BRANCH to $REF...
     git fetch $REPO $BRANCH && git cherry-pick FETCH_HEAD
 fi
 
-echo Diff against $REL
-git diff $REL
+echo Diff against $REF
+git diff $REF
 
 if [ "$INTERACTIVE" == "yes" ] ; then
-    echo -n "Press Enter to interactively rebase $AUTOSQUASH on $REL: "; read foo
-    git rebase -i $AUTOSQUASH $REL || (git rebase --abort; exit 1)
-    echo "Calling addrev $ADDREVOPTS --prnum=$PRNUM $TEAM ${REL}.."
-    addrev $ADDREVOPTS --prnum=$PRNUM $TEAM ${REL}..
+    echo -n "Press Enter to interactively rebase $AUTOSQUASH on $REF: "; read foo
+    git rebase -i $AUTOSQUASH $REF || (git rebase --abort; exit 1)
+    echo "Calling addrev $ADDREVOPTS --prnum=$PRNUM $TEAM ${REF}.."
+    addrev $ADDREVOPTS --prnum=$PRNUM $TEAM ${REF}..
 fi
 
-echo Log since $REL
-git log $REL..
+echo Log since $REF
+git log $REF..
 
-git checkout $REL
+git checkout $REF
 if [ "$INTERACTIVE" != "yes" ] ; then
-    echo -n "Press Enter to non-interactively merge --squash $BRANCH to $REL: "; read foo
+    echo -n "Press Enter to non-interactively merge --squash $BRANCH to $REF: "; read foo
     git merge --ff-only --no-commit --squash $WORK
     AUTHOR=`git show --no-patch --pretty="format:%an <%ae>" $WORK`
     git commit --author="$AUTHOR"
-    addrev $ADDREVOPTS --prnum=$PRNUM $TEAM $REMOTE/${REL}..
+    addrev $ADDREVOPTS --prnum=$PRNUM $TEAM $REMOTE/${REF}..
 else
-    # echo -n "Press Enter to merge to $REL: "; read foo
+    # echo -n "Press Enter to merge to $REF: "; read foo
     git merge --ff-only $WORK
 fi
 
-echo New log since $REMOTE/$REL
-git log $REMOTE/$REL..
+echo New log since $REMOTE/$REF
+git log $REMOTE/$REF..
 
 if [ "$BUILD" == "yes" ] ; then
     echo Rebuilding...
@@ -197,7 +197,7 @@ if [ "$BUILD" == "yes" ] ; then
 fi
 
 while true ; do
-    echo -n "Enter 'y'/'yes' to push to $REMOTE/$REL or 'n'/'no' to abort: "
+    echo -n "Enter 'y'/'yes' to push to $REMOTE/$REF or 'n'/'no' to abort: "
     read x
     x="`echo $x | tr A-Z a-z`"
     if [ "$x" = "y" -o "$x" = "yes" -o "$x" = "n" -o "$x" = "no" ] ; then
@@ -206,5 +206,5 @@ while true ; do
 done
 
 if [ "$x" = "y" -o "$x" = "yes" ] ; then
-    git push -v $REMOTE $REL
+    git push -v $REMOTE $REF
 fi
